// <auto-generated />
using MicroLoja.ProdutoAPI.Infraestrutura.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MicroLoja.ProdutoAPI.Migrations
{
    [DbContext(typeof(ProdutoDbContext))]
    partial class ProdutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MicroLoja.ProdutoAPI.Dominio.Modelos.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icone")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("icone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nome");

                    b.HasKey("Id");

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Smartphones"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Notebooks"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Acessórios"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "TVs e Áudio"
                        });
                });

            modelBuilder.Entity("MicroLoja.ProdutoAPI.Dominio.Modelos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("ImagemUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("imagem_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("produtos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descricao = "Smartphone 5G com tela AMOLED de 6.6” e 256GB de armazenamento.",
                            ImagemUrl = "imagens/produtos/galaxy-s24.jpg",
                            Nome = "Smartphone Galaxy S24",
                            Preco = 4299.90m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 2,
                            Descricao = "Notebook com Intel Core i7, 16GB RAM e SSD de 512GB.",
                            ImagemUrl = "imagens/produtos/dell-inspiron-15.jpg",
                            Nome = "Notebook Dell Inspiron 15",
                            Preco = 5899.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 3,
                            Descricao = "Mouse óptico com iluminação RGB e 6 botões programáveis.",
                            ImagemUrl = "imagens/produtos/mouse-gamer-rgb.jpg",
                            Nome = "Mouse Gamer RGB",
                            Preco = 199.90m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 3,
                            Descricao = "Fone de ouvido sem fio com cancelamento ativo de ruído.",
                            ImagemUrl = "imagens/produtos/fone-bluetooth-anc-pro.jpg",
                            Nome = "Fone Bluetooth ANC Pro",
                            Preco = 799.90m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 4,
                            Descricao = "Smart TV LED 55 polegadas com suporte a HDR10+ e Dolby Audio.",
                            ImagemUrl = "imagens/produtos/smart-tv-55.jpg",
                            Nome = "Smart TV 55” 4K UHD",
                            Preco = 3499.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 3,
                            Descricao = "Teclado mecânico ABNT2 com switches vermelhos e retroiluminação RGB.",
                            ImagemUrl = "imagens/produtos/teclado-mecanico-rgb.jpg",
                            Nome = "Teclado Mecânico RGB",
                            Preco = 459.90m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 4,
                            Descricao = "Caixa de som portátil com 24h de bateria e som estéreo potente.",
                            ImagemUrl = "imagens/produtos/caixa-som-x300.jpg",
                            Nome = "Caixa de Som Bluetooth X300",
                            Preco = 599.90m
                        });
                });

            modelBuilder.Entity("MicroLoja.ProdutoAPI.Dominio.Modelos.Produto", b =>
                {
                    b.HasOne("MicroLoja.ProdutoAPI.Dominio.Modelos.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("MicroLoja.ProdutoAPI.Dominio.Modelos.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
